#!/usr/bin/env python3
"""Fetch one suitable task from Linear for the Ralph loop.

Selection rules (in order):
1. Resume first: if any issue is already "In Progress" (state type: started)
   and NOT labelled "blocked", pick that one (lowest issue number wins).
2. Otherwise pick from backlog/unstarted (state type: backlog or unstarted).
3. Skip parent/epic issues — issues that have sub-issues (children).
   Those are containers; the children are the actual work items.
4. Skip issues labelled "blocked".
5. Among remaining leaf issues, pick the one with the lowest issue number.
   This preserves the intended sequencing of the backlog.

Writes state/current-task.md and prints a machine-readable result line.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from common_linear import get_project_name, graphql

STATE_DIR = os.path.join(os.path.dirname(__file__), "..", "state")


def find_project_id(project_name: str) -> str | None:
    """Find the Linear project ID by name."""
    data = graphql(
        """
        query($filter: ProjectFilter) {
            projects(filter: $filter) {
                nodes { id name }
            }
        }
        """,
        variables={"filter": {"name": {"eq": project_name}}},
    )
    nodes = data.get("projects", {}).get("nodes", [])
    for node in nodes:
        if node["name"] == project_name:
            return node["id"]
    return None


ISSUE_FIELDS = """
    id
    identifier
    title
    description
    priority
    priorityLabel
    url
    labels { nodes { name } }
    state { name type }
    createdAt
    children { nodes { id } }
"""


def fetch_in_progress_issues(project_id: str) -> list[dict]:
    """Fetch issues that are already In Progress (state type: started)."""
    data = graphql(
        f"""
        query($projectId: ID!) {{
            issues(
                filter: {{
                    project: {{ id: {{ eq: $projectId }} }}
                    state: {{ type: {{ in: ["started"] }} }}
                }}
                orderBy: createdAt
                first: 100
            ) {{
                nodes {{ {ISSUE_FIELDS} }}
            }}
        }}
        """,
        variables={"projectId": project_id},
    )
    return data.get("issues", {}).get("nodes", [])


def fetch_candidate_issues(project_id: str) -> list[dict]:
    """Fetch all open/backlog leaf issues from the project.

    Includes children field so we can detect parent/epic issues.
    """
    data = graphql(
        f"""
        query($projectId: ID!) {{
            issues(
                filter: {{
                    project: {{ id: {{ eq: $projectId }} }}
                    state: {{ type: {{ in: ["backlog", "unstarted"] }} }}
                }}
                orderBy: createdAt
                first: 100
            ) {{
                nodes {{ {ISSUE_FIELDS} }}
            }}
        }}
        """,
        variables={"projectId": project_id},
    )
    return data.get("issues", {}).get("nodes", [])


def issue_number(issue: dict) -> int:
    """Extract the numeric part of an identifier like TOM-93 -> 93."""
    try:
        return int(issue["identifier"].split("-")[1])
    except (IndexError, ValueError):
        return 999999


def is_parent(issue: dict) -> bool:
    """Return True if this issue has sub-issues (is an epic/parent container)."""
    children = issue.get("children", {}).get("nodes", [])
    return len(children) > 0


def is_blocked(issue: dict) -> bool:
    """Return True if this issue has the 'blocked' label."""
    labels = issue.get("labels", {}).get("nodes", [])
    return any(label["name"].lower() == "blocked" for label in labels)


def write_current_task(issue: dict) -> None:
    """Write state/current-task.md from the selected issue."""
    os.makedirs(STATE_DIR, exist_ok=True)
    labels = [label["name"] for label in issue.get("labels", {}).get("nodes", [])]
    desc = issue.get("description", "") or "(no description)"

    content = f"""# Current Task

Issue: {issue["identifier"]}
Title: {issue["title"]}
Priority: {issue.get("priorityLabel", "None")}
State: {issue.get("state", {}).get("name", "Unknown")}
Labels: {", ".join(labels) if labels else "none"}
URL: {issue.get("url", "")}

## Description

{desc}

## Notes

- This file was auto-generated by fetch_linear_task.py.
- The agent must implement exactly this issue.
- Follow AGENT.md and PROMPT.md for execution rules.
"""
    path = os.path.join(STATE_DIR, "current-task.md")
    with open(path, "w") as f:
        f.write(content)


def fetch_blocked_issues_with_relations(project_id: str) -> list[dict]:
    """Fetch issues labelled 'blocked' along with their blockedBy relations.

    In Linear's GraphQL API, blocking relations on the blocked issue live
    in ``inverseRelations``.  Each node has ``type="blocks"`` where the
    ``issue`` field is the blocker and ``relatedIssue`` is the blocked issue.
    """
    data = graphql(
        """
        query($projectId: ID!) {
            issues(
                filter: {
                    project: { id: { eq: $projectId } }
                    state: { type: { in: ["backlog", "unstarted", "started"] } }
                    labels: { name: { eq: "blocked" } }
                }
                first: 100
            ) {
                nodes {
                    id
                    identifier
                    labels { nodes { id name } }
                    inverseRelations(first: 50) {
                        nodes {
                            type
                            issue {
                                id
                                identifier
                                state { type }
                            }
                        }
                    }
                }
            }
        }
        """,
        variables={"projectId": project_id},
    )
    return data.get("issues", {}).get("nodes", [])


def remove_label(issue_id: str, label_ids: list[str]) -> None:
    """Update an issue to remove specific label IDs."""
    graphql(
        """
        mutation($id: String!, $labelIds: [String!]!) {
            issueUpdate(id: $id, input: { labelIds: $labelIds }) {
                success
            }
        }
        """,
        variables={"id": issue_id, "labelIds": label_ids},
    )


def auto_unblock(project_id: str) -> list[str]:
    """Check blocked issues and remove the 'blocked' label if all blockers are done.

    Returns list of identifiers that were unblocked.
    """
    COMPLETED_STATE_TYPES = {"completed", "cancelled"}

    blocked_issues = fetch_blocked_issues_with_relations(project_id)
    unblocked = []

    for issue in blocked_issues:
        relations = issue.get("inverseRelations", {}).get("nodes", [])
        blockers = [r["issue"] for r in relations if r["type"] == "blocks"]

        # If no blocker relations exist, we can't auto-resolve — skip.
        if not blockers:
            continue

        all_resolved = all(b["state"]["type"] in COMPLETED_STATE_TYPES for b in blockers)

        if all_resolved:
            # Keep all labels except "blocked".
            labels = issue.get("labels", {}).get("nodes", [])
            remaining_ids = [lb["id"] for lb in labels if lb["name"].lower() != "blocked"]
            remove_label(issue["id"], remaining_ids)
            unblocked.append(issue["identifier"])

    return unblocked


def _filter_eligible(issues: list[dict]) -> list[dict]:
    """Return leaf, non-blocked issues."""
    return [i for i in issues if not is_parent(i) and not is_blocked(i)]


def main():
    project_name = get_project_name()

    project_id = find_project_id(project_name)
    if not project_id:
        print(f"NO_TASK_FOUND: project '{project_name}' not found in Linear.")
        sys.exit(0)

    # --- Phase 0: auto-unblock issues whose blockers are all done ---
    unblocked = auto_unblock(project_id)
    if unblocked:
        print(f"AUTO_UNBLOCKED: {', '.join(unblocked)}")

    # --- Phase 1: resume any in-progress work first ---
    in_progress = fetch_in_progress_issues(project_id)
    resumable = _filter_eligible(in_progress)
    if resumable:
        best = min(resumable, key=issue_number)
        write_current_task(best)

        blocked_wip = [i["identifier"] for i in in_progress if is_blocked(i)]
        if blocked_wip:
            print(f"SKIPPED_BLOCKED_WIP: {', '.join(blocked_wip)}")

        print(f"TASK_RESUMED: {best['identifier']} | {best['title']}")
        return

    # --- Phase 2: pick from backlog/unstarted ---
    issues = fetch_candidate_issues(project_id)
    if not issues:
        print(f"NO_TASK_FOUND: no open issues in project '{project_name}'.")
        sys.exit(0)

    leaves = _filter_eligible(issues)

    if not leaves:
        print(
            "NO_TASK_FOUND: all open issues are parent/epic containers,"
            " blocked, or have no open leaf tasks."
        )
        sys.exit(0)

    # Pick the leaf with the lowest issue number — preserves backlog order.
    best = min(leaves, key=issue_number)

    write_current_task(best)

    # Log skipped parents for visibility.
    parents = [i["identifier"] for i in issues if is_parent(i)]
    if parents:
        print(f"SKIPPED_PARENTS: {', '.join(parents)}")

    blocked = [i["identifier"] for i in issues if is_blocked(i)]
    if blocked:
        print(f"SKIPPED_BLOCKED: {', '.join(blocked)}")

    print(f"TASK_FOUND: {best['identifier']} | {best['title']}")


if __name__ == "__main__":
    main()
